// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mixiaoekppnidetwdwuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1peGlhb2VrcHBuaWRldHdkd3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDU0MzksImV4cCI6MjA3Mzg4MTQzOX0.pG87UCIQlejkOpWCJlBY2QbGPTJCYep5ayPVvWDC8a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});